name: demos_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  pinput: ^1.2.0
  http: ^0.13.3
  intl: ^0.17.0
  intl_phone_field: ^2.0.1
  quiver: ^3.0.1
  permission_handler: ^8.1.4+2
  image_picker: ^0.8.2
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_secure_storage: ^4.2.1
  prompt_dialog: ^1.0.4
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.8
  image_crop: ^0.4.0
  cached_network_image: ^3.1.0
  badges: ^2.0.1
  web_socket_channel: ^2.1.0
  flutter_contacts: ^1.1.0+3
  connectivity: ^3.0.6
  package_info_plus: ^1.3.0
  package_info: ^2.0.2
  loading_overlay: ^0.3.0
  flutter_quill: ^4.0.1
  uuid: 3.0.5
  crypto: ^3.0.1
  expansion_widget: ^0.0.3
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/demos-alpha-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 100
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900

    - family: DemosIcons
      fonts:
        - asset: assets/fonts/DemosIcons.ttf

  assets:
    - assets/images/migala-coin.png
    - assets/images/default-profile.png
    - assets/images/demos-logo.png
    - assets/images/splash-logo.png
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific 'variants', see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this 'flutter' section. Each entry in this list should have a
  # 'family' key with the font family name, and a 'fonts' key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
